/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as AuthClientesRouteImport } from './routes/_auth/clientes'
import { Route as AuthCreditosIndexRouteImport } from './routes/_auth/creditos/index'
import { Route as AuthCreditosCreditoIdRouteImport } from './routes/_auth/creditos/$creditoId'
import { Route as AuthSolicitudesIndexRouteImport } from './routes/_auth/solicitudes/index'
import { Route as AuthSolicitudesSolicitudIdRouteImport } from './routes/_auth/solicitudes/$solicitudId'
import { Route as AuthSolicitudesNuevaRouteImport } from './routes/_auth/solicitudes/nueva'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthClientesRoute = AuthClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCreditosIndexRoute = AuthCreditosIndexRouteImport.update({
  id: '/creditos/',
  path: '/creditos/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCreditosCreditoIdRoute = AuthCreditosCreditoIdRouteImport.update({
  id: '/creditos/$creditoId',
  path: '/creditos/$creditoId',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSolicitudesIndexRoute = AuthSolicitudesIndexRouteImport.update({
  id: '/solicitudes/',
  path: '/solicitudes/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSolicitudesSolicitudIdRoute =
  AuthSolicitudesSolicitudIdRouteImport.update({
    id: '/solicitudes/$solicitudId',
    path: '/solicitudes/$solicitudId',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthSolicitudesNuevaRoute = AuthSolicitudesNuevaRouteImport.update({
  id: '/solicitudes/nueva',
  path: '/solicitudes/nueva',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/login': typeof LoginRoute
  '/clientes': typeof AuthClientesRoute
  '/creditos/$creditoId': typeof AuthCreditosCreditoIdRoute
  '/solicitudes/$solicitudId': typeof AuthSolicitudesSolicitudIdRoute
  '/solicitudes/nueva': typeof AuthSolicitudesNuevaRoute
  '/creditos/': typeof AuthCreditosIndexRoute
  '/solicitudes/': typeof AuthSolicitudesIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/clientes': typeof AuthClientesRoute
  '/': typeof AuthIndexRoute
  '/creditos/$creditoId': typeof AuthCreditosCreditoIdRoute
  '/solicitudes/$solicitudId': typeof AuthSolicitudesSolicitudIdRoute
  '/solicitudes/nueva': typeof AuthSolicitudesNuevaRoute
  '/creditos': typeof AuthCreditosIndexRoute
  '/solicitudes': typeof AuthSolicitudesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/clientes': typeof AuthClientesRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/creditos/$creditoId': typeof AuthCreditosCreditoIdRoute
  '/_auth/solicitudes/$solicitudId': typeof AuthSolicitudesSolicitudIdRoute
  '/_auth/solicitudes/nueva': typeof AuthSolicitudesNuevaRoute
  '/_auth/creditos/': typeof AuthCreditosIndexRoute
  '/_auth/solicitudes/': typeof AuthSolicitudesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/clientes'
    | '/creditos/$creditoId'
    | '/solicitudes/$solicitudId'
    | '/solicitudes/nueva'
    | '/creditos/'
    | '/solicitudes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/clientes'
    | '/'
    | '/creditos/$creditoId'
    | '/solicitudes/$solicitudId'
    | '/solicitudes/nueva'
    | '/creditos'
    | '/solicitudes'
  id:
    | '__root__'
    | '/_auth'
    | '/login'
    | '/_auth/clientes'
    | '/_auth/'
    | '/_auth/creditos/$creditoId'
    | '/_auth/solicitudes/$solicitudId'
    | '/_auth/solicitudes/nueva'
    | '/_auth/creditos/'
    | '/_auth/solicitudes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/clientes': {
      id: '/_auth/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthClientesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/creditos/': {
      id: '/_auth/creditos/'
      path: '/creditos'
      fullPath: '/creditos/'
      preLoaderRoute: typeof AuthCreditosIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/creditos/$creditoId': {
      id: '/_auth/creditos/$creditoId'
      path: '/creditos/$creditoId'
      fullPath: '/creditos/$creditoId'
      preLoaderRoute: typeof AuthCreditosCreditoIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/solicitudes/': {
      id: '/_auth/solicitudes/'
      path: '/solicitudes'
      fullPath: '/solicitudes/'
      preLoaderRoute: typeof AuthSolicitudesIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/solicitudes/$solicitudId': {
      id: '/_auth/solicitudes/$solicitudId'
      path: '/solicitudes/$solicitudId'
      fullPath: '/solicitudes/$solicitudId'
      preLoaderRoute: typeof AuthSolicitudesSolicitudIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/solicitudes/nueva': {
      id: '/_auth/solicitudes/nueva'
      path: '/solicitudes/nueva'
      fullPath: '/solicitudes/nueva'
      preLoaderRoute: typeof AuthSolicitudesNuevaRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthClientesRoute: typeof AuthClientesRoute
  AuthIndexRoute: typeof AuthIndexRoute
  AuthCreditosCreditoIdRoute: typeof AuthCreditosCreditoIdRoute
  AuthSolicitudesSolicitudIdRoute: typeof AuthSolicitudesSolicitudIdRoute
  AuthSolicitudesNuevaRoute: typeof AuthSolicitudesNuevaRoute
  AuthCreditosIndexRoute: typeof AuthCreditosIndexRoute
  AuthSolicitudesIndexRoute: typeof AuthSolicitudesIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthClientesRoute: AuthClientesRoute,
  AuthIndexRoute: AuthIndexRoute,
  AuthCreditosCreditoIdRoute: AuthCreditosCreditoIdRoute,
  AuthSolicitudesSolicitudIdRoute: AuthSolicitudesSolicitudIdRoute,
  AuthSolicitudesNuevaRoute: AuthSolicitudesNuevaRoute,
  AuthCreditosIndexRoute: AuthCreditosIndexRoute,
  AuthSolicitudesIndexRoute: AuthSolicitudesIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
